name: persistent-mtl
version: 0.5.0.1
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
synopsis: Monad transformer for the persistent API
description: |
  A monad transformer and mtl-style type class for using the
  persistent API directly in your monad transformer stack.
category: Database
license: BSD3
extra-source-files:
  - CHANGELOG.md
  - README.md
  - test/goldens/**/*.golden

ghc-options: -Wall

github: brandonchinn178/persistent-mtl

library:
  source-dirs: src
  dependencies:
    - base >= 4.14 && < 5
    - conduit >= 1.3.4 && < 1.4
    - containers >= 0.6 && < 0.7
    - exceptions >= 0.10 && < 0.11
    - monad-logger >= 0.3 && < 0.4
    - mtl >= 2.2.2 && < 2.4
    - persistent >= 2.13 && < 2.15
    - resource-pool >= 0.2.3.2 && < 1
    - resourcet >= 1.2.4 && < 1.4
    - text >= 1.2.4 && < 2.1
    - transformers >= 0.5.6 && < 0.7
    - unliftio >= 0.2 && < 0.3
    - unliftio-core >= 0.2 && < 0.3
    - unliftio-pool >= 0.2 && < 1

  when:
    # https://gitlab.haskell.org/ghc/ghc/-/issues/20836
    - condition: >
        impl(ghc >= 9.2.0) && impl(ghc < 9.3) ||
        impl(ghc >= 9.4.0) && impl(ghc < 9.4.3)
      buildable: false

tests:
  persistent-mtl-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -F -pgmF=tasty-autocollect
    build-tools:
      - tasty-autocollect:tasty-autocollect
    dependencies:
      - base
      - bytestring
      - conduit
      - containers
      - esqueleto
      - explainable-predicates
      - monad-logger
      - persistent
      - persistent-mtl
      - persistent-postgresql
      - persistent-sqlite
      - persistent-template
      - resource-pool
      - resourcet
      - tasty
      - tasty-autocollect
      - tasty-golden
      - tasty-hunit
      - text
      - unliftio
