name: persistent-mtl
version: 0.5.1
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
synopsis: Monad transformer for the persistent API
description: |
  A monad transformer and mtl-style type class for using the
  persistent API directly in your monad transformer stack.
category: Database
license: BSD3
extra-source-files:
  - CHANGELOG.md
  - README.md
  - test/**/*.snap.md

ghc-options: -Wall -Wcompat -Wunused-packages

github: brandonchinn178/persistent-mtl

library:
  source-dirs: src
  dependencies:
    - base < 5
    - conduit
    - containers
    - exceptions
    - monad-logger
    - mtl
    - persistent
    - resource-pool
    - resourcet
    - text
    - transformers
    - unliftio
    - unliftio-core
    - unliftio-pool

  when:
    # https://gitlab.haskell.org/ghc/ghc/-/issues/20836
    - condition: >
        impl(ghc >= 9.4.0) && impl(ghc < 9.4.3)
      buildable: false

tests:
  persistent-mtl-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -F -pgmF=skeletest-preprocessor
    build-tools:
      - skeletest:skeletest-preprocessor
    dependencies:
      - base
      - bytestring
      - conduit
      - containers
      - esqueleto >= 3.5.14.0
      - monad-logger
      - persistent
      - persistent-mtl
      - persistent-postgresql >= 2.13.0.0
      - persistent-sqlite >= 2.13.0.3
      - resource-pool
      - resourcet
      - skeletest >= 0.2.1
      - text
      - unliftio
