{-|
Module: Database.Persist.Sql.Shim

Defines all the @persistent@ functions lifted into 'MonadSqlQuery', and
re-exports a version of the @Database.Persist.Sql@ module replacing each
function with the lifted version.

This file is autogenerated, to keep it in sync with
@Database.Persist.Monad.Shim@.
-}

{- THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED MANUALLY -}

{-# LANGUAGE CPP #-}

module Database.Persist.Sql.Shim (
  module Database.Persist.Sql,
  get,
  getMany,
  getJust,
  getJustEntity,
  getEntity,
  belongsTo,
  belongsToJust,
  insert,
  insert_,
  insertMany,
  insertMany_,
  insertEntityMany,
  insertKey,
  repsert,
  repsertMany,
  replace,
  delete,
  update,
  updateGet,
  insertEntity,
  insertRecord,
  getBy,
#if MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  getByValue,
#endif
  checkUnique,
#if MIN_VERSION_persistent(2,11,0)
  checkUniqueUpdateable,
#endif
  deleteBy,
  insertUnique,
#if MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  upsert,
#endif
  upsertBy,
  putMany,
#if MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  insertBy,
#endif
  insertUniqueEntity,
  replaceUnique,
#if MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
#if !MIN_VERSION_persistent(2,10,0)
  onlyUnique,
#endif
  selectSourceRes,
  selectFirst,
  selectKeysRes,
  count,
#if MIN_VERSION_persistent(2,11,0)
  exists,
#endif
  selectSource,
  selectKeys,
  selectList,
  selectKeysList,
  updateWhere,
  deleteWhere,
  deleteWhereCount,
  updateWhereCount,
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascade,
#endif
#if !MIN_VERSION_persistent(2,13,0)
  deleteCascadeWhere,
#endif
  parseMigration,
  parseMigration',
  printMigration,
  showMigration,
  getMigration,
  runMigration,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationQuiet,
#endif
  runMigrationSilent,
  runMigrationUnsafe,
#if MIN_VERSION_persistent(2,10,2)
  runMigrationUnsafeQuiet,
#endif
  getFieldName,
  getTableName,
  withRawQuery,
  rawQueryRes,
  rawQuery,
  rawExecute,
  rawExecuteCount,
  rawSql,
  transactionSave,
#if MIN_VERSION_persistent(2,9,0)
  transactionSaveWithIsolation,
#endif
  transactionUndo,
#if MIN_VERSION_persistent(2,9,0)
  transactionUndoWithIsolation,
#endif
  unsafeLiftSql,
  ) where

import Database.Persist.Monad.Shim (
    get,
    getMany,
    getJust,
    getJustEntity,
    getEntity,
    belongsTo,
    belongsToJust,
    insert,
    insert_,
    insertMany,
    insertMany_,
    insertEntityMany,
    insertKey,
    repsert,
    repsertMany,
    replace,
    delete,
    update,
    updateGet,
    insertEntity,
    insertRecord,
    getBy,
#if MIN_VERSION_persistent(2,10,0)
    getByValue,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    getByValue,
#endif
    checkUnique,
#if MIN_VERSION_persistent(2,11,0)
    checkUniqueUpdateable,
#endif
    deleteBy,
    insertUnique,
#if MIN_VERSION_persistent(2,10,0)
    upsert,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    upsert,
#endif
    upsertBy,
    putMany,
#if MIN_VERSION_persistent(2,10,0)
    insertBy,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    insertBy,
#endif
    insertUniqueEntity,
    replaceUnique,
#if MIN_VERSION_persistent(2,10,0)
    onlyUnique,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    onlyUnique,
#endif
    selectSourceRes,
    selectFirst,
    selectKeysRes,
    count,
#if MIN_VERSION_persistent(2,11,0)
    exists,
#endif
    selectSource,
    selectKeys,
    selectList,
    selectKeysList,
    updateWhere,
    deleteWhere,
    deleteWhereCount,
    updateWhereCount,
#if !MIN_VERSION_persistent(2,13,0)
    deleteCascade,
#endif
#if !MIN_VERSION_persistent(2,13,0)
    deleteCascadeWhere,
#endif
    parseMigration,
    parseMigration',
    printMigration,
    showMigration,
    getMigration,
    runMigration,
#if MIN_VERSION_persistent(2,10,2)
    runMigrationQuiet,
#endif
    runMigrationSilent,
    runMigrationUnsafe,
#if MIN_VERSION_persistent(2,10,2)
    runMigrationUnsafeQuiet,
#endif
    getFieldName,
    getTableName,
    withRawQuery,
    rawQueryRes,
    rawQuery,
    rawExecute,
    rawExecuteCount,
    rawSql,
    transactionSave,
#if MIN_VERSION_persistent(2,9,0)
    transactionSaveWithIsolation,
#endif
    transactionUndo,
#if MIN_VERSION_persistent(2,9,0)
    transactionUndoWithIsolation,
#endif
    unsafeLiftSql
    )
import Database.Persist.Sql hiding (
    get,
    getMany,
    getJust,
    getJustEntity,
    getEntity,
    belongsTo,
    belongsToJust,
    insert,
    insert_,
    insertMany,
    insertMany_,
    insertEntityMany,
    insertKey,
    repsert,
    repsertMany,
    replace,
    delete,
    update,
    updateGet,
    insertEntity,
    insertRecord,
    getBy,
#if MIN_VERSION_persistent(2,10,0)
    getByValue,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    getByValue,
#endif
    checkUnique,
#if MIN_VERSION_persistent(2,11,0)
    checkUniqueUpdateable,
#endif
    deleteBy,
    insertUnique,
#if MIN_VERSION_persistent(2,10,0)
    upsert,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    upsert,
#endif
    upsertBy,
    putMany,
#if MIN_VERSION_persistent(2,10,0)
    insertBy,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    insertBy,
#endif
    insertUniqueEntity,
    replaceUnique,
#if MIN_VERSION_persistent(2,10,0)
    onlyUnique,
#endif
#if !MIN_VERSION_persistent(2,10,0)
    onlyUnique,
#endif
    selectSourceRes,
    selectFirst,
    selectKeysRes,
    count,
#if MIN_VERSION_persistent(2,11,0)
    exists,
#endif
    selectSource,
    selectKeys,
    selectList,
    selectKeysList,
    updateWhere,
    deleteWhere,
    deleteWhereCount,
    updateWhereCount,
#if !MIN_VERSION_persistent(2,13,0)
    deleteCascade,
#endif
#if !MIN_VERSION_persistent(2,13,0)
    deleteCascadeWhere,
#endif
    parseMigration,
    parseMigration',
    printMigration,
    showMigration,
    getMigration,
    runMigration,
#if MIN_VERSION_persistent(2,10,2)
    runMigrationQuiet,
#endif
    runMigrationSilent,
    runMigrationUnsafe,
#if MIN_VERSION_persistent(2,10,2)
    runMigrationUnsafeQuiet,
#endif
    getFieldName,
    getTableName,
    withRawQuery,
    rawQueryRes,
    rawQuery,
    rawExecute,
    rawExecuteCount,
    rawSql,
    transactionSave,
#if MIN_VERSION_persistent(2,9,0)
    transactionSaveWithIsolation,
#endif
    transactionUndo,
#if MIN_VERSION_persistent(2,9,0)
    transactionUndoWithIsolation,
#endif
    )

